name: Atualização Automática de Dados

on:
  schedule:
    # Executa todos os dias à meia-noite (UTC)
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Permite execução manual do workflow

permissions:
  contents: write

jobs:
  atualizar-dados:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Extrair dados do BCB
        run: |
          python -m src.dados.extratores.bcb
      
      - name: Processar previsões
        run: |
          python -m src.dados.processadores.previsao
      
      - name: Commit e push das alterações
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -f data/*.json
          git commit -m "Atualização automática de dados [skip ci]" || echo "Sem alterações para commit"
          git push
